#!/usr/bin/env python

import re, os, sys

if os.path.exists('junk.txt'):
    print """
Sorry, the file 'junk.txt' is still there.
"""

else:
    print """
The junk file has been deleted!

The nineth character of the solution is '%s'
"""%(chr(84))

n = len(os.listdir('data'))
if n > 0:
    print """The data/ directory still contains %i files.
"""%n
else:
    print """The data directory is empty.

The tenth character of the solution is '%s'
"""%(chr(69))

