#!/usr/bin/env python

import re, os, sys

if not os.path.exists('solution'):
    print """
Sorry, the directory 'solution' is not there.
"""
elif not os.path.exists('solution/code.txt'):
    print """
Sorry, the file 'code.txt' was not found in the 
directory 'solution'.
"""
else:
    out = """
Worked! The next two characters of the solution are:
    '"""
    for line in open('solution/code.txt'):
        char = chr(int(line.strip()))
        out += char
    out += "'\n"

    print out
