#!/usr/bin/env python

import re, os, sys

var = os.environ.get('SOLUTION','--- not set ---')

if re.search("6\.3",var):
    print("""
The environment variable was set correctly. 

The 19th character is '{}'.
""".format(chr(73)))

else:
    print("""
Sorry, in the SOLUTION variable the value '{}' was found 
instead of '6.3'.
""".format(var))
