#!/usr/bin/env python

import re, os, sys

answer = input("""
Please enter the IP address of www.google.com
(an IP address is something that looks like this:
    91.198.174.232
)
""")

if re.search("\d+\.\d+\.\d+\.\d+",answer):
    print("""
Correct. 

The 20th character is '{}'.
""".format(chr(67)))

else:
    print("""
Sorry, please try again.
""")
